---
- name: restart docker-compose
  shell: |
    docker-compose up -d
  args:
    chdir: /var/apps

- name: restart a2ms
  shell: |
    docker-compose up -d --build a2m2
  args:
    chdir: /var/apps

- name: restart a2ms-api
  shell: |
    docker-compose up -d --build a2m2-api
  args:
    chdir: /var/apps
