---
- hosts: a2ms
  become: yes
  remote_user: ken
  roles:
    - machine
    - packages
    - mongodb
    - user
    - docker
    - apps

- hosts: do
  become: yes
  remote_user: root
  roles:
    - packages
    - machine
    - mongodb
    - docker
    - apps
