---
- name: add apt key for mongodb
  apt_key: >
    keyserver='hkp://keyserver.ubuntu.com:80'
    id='7F0CEB10'

- name: add apt key for docker-engine
  apt_key: >
    keyserver="hkp://p80.pool.sks-keyservers.net:80"
    id="58118E89F3A912897C070ADBF76221572C52609D"

- name: add apt repo for mongodb
  apt_repository: >
    repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse'
    state=present

- name: add apt repo for docker-engine
  apt_repository: >
    repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main'
    state=present

- name: get kernel name
  shell: uname -r
  register: kernel_name
  changed_when: false
  always_run: yes

- name: install apt packages
  apt: pkg={{ item }} force=yes update_cache=yes
  with_items:
    - git
    - python
    - python-pip
    - zsh
    - curl
    - wget
    - ufw
    - linux-image-extra-{{kernel_name.stdout}}
    - mongodb-org
    - docker-engine

- name: install pip packages
  pip: name=docker-compose
