---
- name: deny all port defaultly
  ufw: state=enabled policy=deny

- name: open tcp ports
  ufw: state=enabled rule=allow proto=tcp port={{ item }}
  with_items:
    - 80
    - 443

- name: allow connnection from docker to mariadb
  ufw: state=enabled rule=allow proto=tcp port=3306 src=172.17.42.1/16

- name: limit port 22
  ufw: state=enabled rule=limit proto=tcp port=22

- name: enable and start services
  service: name={{ item }} enabled=yes state=started
  with_items:
    - mysql
    - docker

- name: mkdir /var/shared # refuse to modify shared files
  file: >
    path=/var/shared state=directory
    owner=root group=root mode=1777

# upload dir
- name: mkdir /var/shared/a2ms
  file: >
    path=/var/shared/a2ms state=directory
    owner=root group=root mode=0777

